### ISSUE TITLE
Build custom plugin in Shopware 5.2.6

### ISSUE THREAD

**Issue by nik4152** [shopware/devdocs#381]
Hi, how build plugin in shopware 5.2.6?
Build Backend plugin new clear window (page)?
I created plugin aded menu item and when click go to page plugin then show error "Not Found 404 app"

**Comment by mitelg** [comment]
Hi @nik4152 
have you already checked our articles here? https://developers.shopware.com/developers-guide/
at the bottom you find `Backend and ExtJS resources`. maybe this will help you

**Comment by nik4152** [comment]
Hi @mitelg  how in plugin extend theme template detail cre

**Comment by nik4152** [comment]
Hi @mitelg how in plugin extend template detail?

I subscribe event
```
$this->subscribeEvent(
	'Enlight_Controller_Front_DispatchLoopStartup',
	'onStartDispatch'
);
```

add folder extend template plugin
`Shopware()->Template()->addTemplateDir($this->Path() . 'Views');
`

I do exactly the same structure as a the theme in engine\Shopware\Plugins\Local\Frontend\PluginDir\Views\frontend\detail\buy.tpl update the cache and compile, check the page and then nothing has changed. What am I doing wrong?

**Comment by mitelg** [comment]
hi @nik4152 
at first you are writing about a backend plugin and now you want to extend the detail page of a product in the store front. I don't get what you really want :blush: 
Beside this, I think this place is not the right one for asking things about developing plugins :wink: 
Please open a new thread with your question and maybe example code in our forum https://forum.shopware.com/
There you will reach much more people than here. Let me know, when you opened the thread and we will see, what we can do.
I will close this issue for now, because is not really an issue related to our developer documentation :wink:
